name: Slack Username
description: Fetch Slack Username by GitHub Associated Email
author: 'Camis Inc'
inputs:
  username:
    description: The username of the user in GitHub to fetch in Slack
    required: optional
  github-token:
    description: The github token used to retrieve information about the provided GitHub user 
    required: true
  slack-token:
    description: The Slack API Token used to fetch Slack users
    required: true
outputs:
  member-id:
    description: The matching Slack user's unique member id
  username:
    description: The matching Slack user's username
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'at-sign'
  color: 'green'